apiVersion: apps/v1
kind: Deployment

metadata:
  name: url-deployment
  labels:
    app: url-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-deployment
  template:
    metadata:
      labels:
        app: url-deployment
    spec:
      containers:
        - name: url-deployment
          image: sweptwings/url-shortner_url-service:46e22a8
          ports:
            - containerPort: 80

          env:
            # - name: REDIS_HOST
            #   valueFrom:
            #     configMapKeyRef:
            #       name: shortify-config
            #       key: redis_host
            - name: REDIS_HOST
              value: "redis"
---
apiVersion: v1
kind: Service

metadata:
  name: url-node-service

spec:
  type: NodePort
  selector:
    app: url-deployment

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: app-group
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/success-codes: "404"
    alb.ingress.kubernetes.io/group.order: '1'
spec:
  rules:
    - http:
        paths:
          - path: /url
            pathType: Prefix
            backend:
              service:
                name: url-node-service
                port:
                  number: 80